### ISSUE TITLE
Replicate dependabot changes in inner repo

### ISSUE THREAD

**Issue by john-sandall** [CoefficientSystems/coefficient-cookiecutter#57]
List of dependabot PRs which made changes to outer repo but not inner repo:
- #29
- #32
- #41
- #44
- #46
- #49
- #50

**Comment by hicksl** [comment]
- [ ] https://github.com/CoefficientSystems/coefficient-cookiecutter/pull/29
- [ ] https://github.com/CoefficientSystems/coefficient-cookiecutter/pull/32
- [ ] https://github.com/CoefficientSystems/coefficient-cookiecutter/pull/41
- [ ] https://github.com/CoefficientSystems/coefficient-cookiecutter/pull/44
- [ ] https://github.com/CoefficientSystems/coefficient-cookiecutter/pull/46
- [ ] https://github.com/CoefficientSystems/coefficient-cookiecutter/pull/49
- [ ] https://github.com/CoefficientSystems/coefficient-cookiecutter/pull/50
